---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: danm-cni
  namespace: kube-system
spec:
  selector:
    matchLabels:
      danm.k8s.io: danm-cni
  template:
    metadata:
      labels:
        danm.k8s.io: danm-cni
    spec:
      containers:
        - name: danm-cni
          image: rasp02:5000/danm-cni-plugins:ed6b0c57 
          imagePullPolicy: Always 
          volumeMounts:
            - name: host-cni
              mountPath: /host/cni
            - name: host-net-d
              mountPath: /host/net.d
      hostNetwork: true
      terminationGracePeriodSeconds: 0
      volumes:
        - name: host-cni
          hostPath:
            path: /opt/cni/bin
        - name: host-net-d
          hostPath:
            path: /etc/cni/net.d
